#!/bin/bash

# install CRAN packages
R -e 'install.packages(c("googleway", "restatis"), repos = "https://ftp.fau.de/cran/", dependencies = TRUE)' # Google API access, Destatis GENEIS access
R -e 'remotes::install_github("sumtxt/bonn", force=TRUE)' # INKAR API access
R -e 'remotes::install_github("sumtxt/ags", force=TRUE)' # AGS crosswalks